name: Automated API tests using Newman

on:
  push:
  workflow_dispatch:

jobs:
  newman-api-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Newman collection
        run: newman run collections/test.postman_collection.json -e environments/qa.postman_environment.json
