name: Automated API tests using Newman via Postman API

on:
  push:
  workflow_dispatch:

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Newman and reporters
        run: |
          npm install -g newman newman-reporter-html

      - name: Run Postman Collection from Postman Cloud
        run: |
          newman run "https://api.postman.com/collections/44208231-1c6a7981-4be4-4441-9435-6397f396a1b5?apikey=${{ secrets.POSTMAN_API_KEY }}" \
            -e "https://api.postman.com/environments/286eeae8-e641-4a0c-a02a-339b10b1b21e?apikey=${{ secrets.POSTMAN_API_KEY }}" \
            --reporters cli,html \
            --reporter-html-export newman-report.html
