name: Automated API tests using Newman

on:
  push:
  workflow_dispatch:

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Newman and reporters
        run: |
          npm install -g newman newman-reporter-html

      - name: Run Postman Collection with packages
        run: |
          newman run postman/your_collection.json \
            -e postman/your_environment.json \
            --reporters cli,html \
            --reporter-html-export newman-report.html
